"""
FraudShield AI - PDF Report Generator
Generates downloadable fraud analysis reports using fpdf2.
"""
from fpdf import FPDF
from datetime import datetime
import os


class FraudReport(FPDF):
    def header(self):
        self.set_fill_color(15, 23, 42)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(99, 179, 237)
        self.cell(0, 10, "  FraudShield AI — Fraud Detection Report", ln=True, align="L")
        self.set_text_color(148, 163, 184)
        self.set_font("Helvetica", "", 8)
        self.cell(0, 5, f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}  |  CONFIDENTIAL", ln=True)
        self.ln(3)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, f"FraudShield AI  |  Page {self.page_no()}  |  Confidential", align="C")

    def section_title(self, title: str):
        self.set_fill_color(30, 41, 59)
        self.set_text_color(99, 179, 237)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, f"  {title}", ln=True, fill=True)
        self.ln(2)

    def kv_row(self, key: str, value: str, highlight: bool = False):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(148, 163, 184)
        self.cell(70, 7, key, border="B")
        self.set_font("Helvetica", "", 9)
        if highlight:
            self.set_text_color(248, 113, 113)
        else:
            self.set_text_color(226, 232, 240)
        self.cell(0, 7, str(value), border="B", ln=True)
        self.set_text_color(0, 0, 0)


def generate_transaction_report(transaction: dict, assessment, output_dir: str = "reports") -> str:
    """Generate a single-transaction fraud report PDF."""
    os.makedirs(output_dir, exist_ok=True)
    txn_id = transaction.get("Transaction_ID", "UNKNOWN")
    filename = f"fraud_report_{txn_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(output_dir, filename)

    pdf = FraudReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(15, 25, 15)
    pdf.add_page()

    # Risk Badge
    risk_level = assessment.risk_level
    rgb = {"Low": (0, 200, 81), "Medium": (255, 136, 0), "High": (255, 68, 68)}.get(risk_level, (100, 100, 100))
    pdf.set_fill_color(*rgb)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 14, f"  {assessment.risk_emoji}  {risk_level.upper()} RISK  —  Score: {assessment.risk_score}/100", ln=True, fill=True)
    pdf.ln(4)

    # Transaction Details
    pdf.section_title("Transaction Details")
    for k, v in {
        "Transaction ID": txn_id,
        "User ID": transaction.get("User_ID", "N/A"),
        "Amount": f"${transaction.get('Transaction_Amount', 0):,.2f}",
        "Type": transaction.get("Transaction_Type", "N/A"),
        "Location": transaction.get("Location", "N/A"),
        "Device": transaction.get("Device_Type", "N/A"),
        "Merchant Category": transaction.get("Merchant_Category", "N/A"),
        "Card Type": transaction.get("Card_Type", "N/A"),
        "Account Balance": f"${transaction.get('Account_Balance', 0):,.2f}",
        "Card Age (months)": str(transaction.get("Card_Age", "N/A")),
        "Daily Txn Count": str(transaction.get("Daily_Transaction_Count", "N/A")),
        "Prior Fraud History": "Yes" if transaction.get("Previous_Fraudulent_Activity") else "No",
    }.items():
        highlight = k == "Prior Fraud History" and transaction.get("Previous_Fraudulent_Activity")
        pdf.kv_row(k, v, highlight=bool(highlight))

    pdf.ln(5)

    # Risk Assessment
    pdf.section_title("Risk Assessment")
    pdf.kv_row("Fraud Probability", f"{assessment.fraud_probability:.2%}", highlight=assessment.fraud_probability > 0.65)
    pdf.kv_row("Risk Score", f"{assessment.risk_score} / 100", highlight=assessment.risk_score >= 65)
    pdf.kv_row("Risk Level", risk_level, highlight=risk_level == "High")
    pdf.ln(5)

    # Recommendation
    pdf.section_title("Recommendation")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(226, 232, 240)
    pdf.multi_cell(0, 7, assessment.recommendation)
    pdf.ln(5)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, (
        "DISCLAIMER: This report is generated by an AI model and is intended for informational purposes only. "
        "FraudShield AI does not guarantee 100% accuracy. Human review is recommended for high-risk transactions."
    ))

    pdf.output(filepath)
    return filepath


def generate_summary_report(stats: dict, model_metrics: dict, output_dir: str = "reports") -> str:
    """Generate a summary/executive PDF report."""
    os.makedirs(output_dir, exist_ok=True)
    filename = f"fraudshield_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(output_dir, filename)

    pdf = FraudReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(15, 25, 15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(226, 232, 240)
    pdf.cell(0, 12, "Executive Summary — Fraud Analytics", ln=True)
    pdf.ln(3)

    pdf.section_title("Platform Statistics")
    for k, v in {
        "Total Transactions Analyzed": f"{stats.get('total_transactions', 0):,}",
        "High Risk Alerts": str(stats.get("high_risk_count", 0)),
        "Medium Risk Transactions": str(stats.get("medium_risk_count", 0)),
        "Low Risk Transactions": str(stats.get("low_risk_count", 0)),
        "Open Unresolved Alerts": str(stats.get("open_alerts", 0)),
    }.items():
        pdf.kv_row(k, v)

    pdf.ln(5)
    pdf.section_title("Model Performance")
    for k, v in model_metrics.items():
        pdf.kv_row(str(k), str(v))

    pdf.output(filepath)
    return filepath
